// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlDH2Wl3reowLGi8m7QOW-WQdpZKeoAuc',
    appId: '1:662548107081:web:38d666587533665918d498',
    messagingSenderId: '662548107081',
    projectId: 'chat-app-c7b50',
    authDomain: 'chat-app-c7b50.firebaseapp.com',
    storageBucket: 'chat-app-c7b50.appspot.com',
    measurementId: 'G-8BMR2EHC1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3T4maH_tV1Wquqh1SOJKoKop1h_YabZg',
    appId: '1:662548107081:android:98aa31e5c7b0507f18d498',
    messagingSenderId: '662548107081',
    projectId: 'chat-app-c7b50',
    storageBucket: 'chat-app-c7b50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4Q8Xm10lKar4IBWWn9JsC15yy7LhYOxw',
    appId: '1:662548107081:ios:8676fee3e0e5c8a318d498',
    messagingSenderId: '662548107081',
    projectId: 'chat-app-c7b50',
    storageBucket: 'chat-app-c7b50.appspot.com',
    iosClientId: '662548107081-b6d0e82dl0fufuek1oqu3pv4j78bbqn7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4Q8Xm10lKar4IBWWn9JsC15yy7LhYOxw',
    appId: '1:662548107081:ios:8676fee3e0e5c8a318d498',
    messagingSenderId: '662548107081',
    projectId: 'chat-app-c7b50',
    storageBucket: 'chat-app-c7b50.appspot.com',
    iosClientId: '662548107081-b6d0e82dl0fufuek1oqu3pv4j78bbqn7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
